#ifndef CONSTANTS_H
#define CONSTANTS_H

#define XTAL_0V_ADC               0
#define XTAL_1V_ADC               1050
#define XTAL_2V_ADC               2250
#define XTAL_ADC_TOL              300

#define NEXTION_RT_A_GREYOUT_PIC	118
#define NEXTION_RT_A_PIC			119
#define NEXTION_RT_B_GREYOUT_PIC	120
#define NEXTION_RT_B_PIC			121
#define NEXTION_RDSBAR_0			206
#define NEXTION_RDSBAR_1			207
#define NEXTION_RDSBAR_2			208
#define NEXTION_RDSBAR_3			209
#define NEXTION_RDSBAR_4			210
#define NEXTION_MUSICLOGO_GREYOUT	38
#define NEXTION_MUSICLOGO			39
#define NEXTION_SPEECHLOGO_GREYOUT	40
#define NEXTION_SPEECHLOGO			41
#define NEXTION_RDSLOGO				18
#define NEXTION_RDSLOGO_GREYOUT		19
#define NEXTION_COLOR_WHITE			65535
#define NEXTION_COLOR_YELLOW		65504
#define NEXTION_TALOGO_GREYOUT		42
#define NEXTION_TALOGO				43
#define NEXTION_TPLOGO_GREYOUT		44
#define NEXTION_TPLOGO				45
#define NEXTION_EONLOGO_GREYOUT		52
#define NEXTION_EONLOGO				53
#define NEXTION_RTPLUSLOGO_GREYOUT  5
#define NEXTION_RTPLUSLOGO			4

#endif